clanServices/zerotier: reinit moons if it previously failed and created an empty moon config
If `zerotier-idtool initmoon /var/lib/zerotier-one/identity.public > /var/lib/zerotier-one/moon.json` fails it creates an empty file `/var/lib/zerotier-one/moon.json`.

After one failure, successive attempts to run the `init-zerotier-install-moons` didn't run `zerotier-idtool initmoon` again resulting in the next command `.../genmoon /var/lib/zerotier-one/moon.json ...` failing due to invalid json (empty file). (exact error message below)

This adds a `-s /var/lib/zerotier-one/moon.json` condition so it also runs if the file exists, but is empty.

The test also has that `-s` condition, so it fails if the created moon config is empty.

Error message when genmoon fails on empty moon.json:
```py
Traceback (most recent call last):
  File "/nix/store/5h5sb0q1ijmfs71a2j00yxwknc99h4bn-genmoon/bin/genmoon", line 34, in <module>
    main()
    ~~~~^^
  File "/nix/store/5h5sb0q1ijmfs71a2j00yxwknc99h4bn-genmoon/bin/genmoon", line 21, in main
    moon_json = json.loads(Path(moon_json_path).read_text())
  File "/nix/store/60m4rxhg2fldqaak400c0lry96ijrzqn-python3-3.13.13/lib/python3.13/json/__init__.py", line 352, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/nix/store/60m4rxhg2fldqaak400c0lry96ijrzqn-python3-3.13.13/lib/python3.13/json/decoder.py", line 345, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/60m4rxhg2fldqaak400c0lry96ijrzqn-python3-3.13.13/lib/python3.13/json/decoder.py", line 363, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```