checks/installation: Override `Nix` used by `nixos-anywhere`
Override the `Nix` version used by `nixos-anywhere` used by the `clan`
CLI.

Nix 2.31 introduced stricter permission canonicalization that unconditionally
chmods directories to 0555 during `nix copy` [^nix-perms] operations.
In the nixos test we have the following file overlay file structure
`findmnt` (elided and compacted for brevity):

```shell-session
├─/nix/.ro-store  nix-store  9p         rw,relatime,cache=f,access=client,msize=16384,trans=virtio
├─/nix/.rw-store  tmpfs      tmpfs      rw,relatime,mode=755
├─/nix/store      overlay    overlay    rw,relatime,lowerdir=/mnt-root/nix/.ro-store,upperdir=/mnt-root/nix/.rw-store/upper,workdir=/mnt-root/nix/.rw-store/work,uuid=on
│ └─/nix/store    overlay    overlay    ro,nosuid,nodev,relatime,lowerdir=/mnt-root/nix/.ro-store,upperdir=/mnt-root/nix/.rw-store/upper,workdir=/mnt-root/nix/.rw-store/work,uuid=on
```

This means that the host store is shared and new paths are written to
the writeable layer, but old paths that don't need to be written will be
canonicalized, which fails, because we don't have the permissions to
change the permissions of the read only layer.

The error message we got:

```shell-session
copying path '/nix/store/0dqzmxlgkmw057ffz0cpcbszg17yfmrk-publicsuffix-list-0-unstable-2025-08-28' to 'ssh://root@localhost'...
error: chmod "/nix/store/0dqzmxlgkmw057ffz0cpcbszg17yfmrk-publicsuffix-list-0-unstable-2025-08-28": Operation not permitted
```

[^nix-perms]: Nix Permission change: https://github.com/NixOS/nix/pull/13526